apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: java-quarkus-keufvwwz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-keufvwwz 
  name: java-quarkus-keufvwwz
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkus-keufvwwz
    weight: 100 
